name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Permissions for the GITHUB_TOKEN.
permissions: {}

jobs:
  build_test:
    name: Call build and test action
    permissions:
      contents: read # The contents: read is not necessary for a public repository but it is necessary for the reusable workflow, which has it as a requirement.
    uses: andrew-field/reusable-workflows/.github/workflows/build-test.yml@12ab0b3e1e75cce018ed57ec1396a583b8a505be # v1.5.23
    
