name: Pinact

on:
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Permissions for the GITHUB_TOKEN.
permissions: {}

jobs:
  lint:
    name: Run pinact
    permissions:
      contents: read # The contents: read is not necessary for a public repository but it is necessary for the reusable workflow.
    uses: andrew-field/reusable-workflows/.github/workflows/pinact.yml@master

    # Needs to inherit more than the GITHUB_TOKEN to commit changes and trigger Github Actions CI checks. APP_ID and APP_PRIVATE_KEY (for the github app) need to be added as a secret.
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
