name: Refresh go report card

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Permissions for the GITHUB_TOKEN.
permissions: {}

jobs:
  post-request:
    name: Call refresh go report card action
    uses: andrew-field/reusable-workflows/.github/workflows/refresh-go-report-card.yml@8c28e170c5d4039c41c0f85013b50fd5432bf6a3 # v1.5.8
