name: Refresh go report card

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Permissions for the GITHUB_TOKEN.
permissions: {}

jobs:
  post-request:
    name: Call refresh go report card action
    uses: andrew-field/reusable-workflows/.github/workflows/refresh-go-report-card.yml@0e8a348c69366992354938d2bb2345b51d5e79c9 # v1.5.17
