name: Super Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Permissions for the GITHUB_TOKEN.
permissions: {}

jobs:
  lint:
    name: Lint code base
    permissions:
      contents: read # The contents: read is not necessary for a public repository but it is necessary for the reusable workflow.
    uses: andrew-field/reusable-workflows/.github/workflows/super-linter.yml@master
